[workspace]
resolver = "2"
members = [
    "crates/atomic",
    "crates/cef",
    "crates/net", "crates/storage",
    "crates/platform-apis", "crates/profile", "crates/ipc", "crates/security",
    "crates/automation", "crates/import",
    "crates/neutron",
    "crates/neutron/html", "crates/neutron/css", "crates/neutron/layout-engine",
    "crates/neutron/atoms", "crates/neutron/dom", "crates/neutron/js-runtime",
    "crates/neutron/js-runtime/quickjs-sys",
    "crates/neutron/render", "crates/neutron/webgl", "crates/neutron/workers",
    "crates/neutron/image_decode",
    "xtask",
]
