[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
image_decode = { path = "../image_decode" }
layout-engine = { path = "../layout-engine" }
wgpu = "0.20"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.3"

[dev-dependencies]
css = { path = "../css" }
dom = { path = "../dom" }
