[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28"
egui = "0.28"
profile = { path = "../../crates/profile" }
automation = { path = "../../crates/automation" }
js-runtime = { path = "../../crates/js-runtime" }
platform-apis = { path = "../../crates/platform-apis" }
net = { path = "../../crates/net" }
url = "2.5.8"
security = { path = "../../crates/security" }
import = { path = "../../crates/import" }
render = { path = "../../crates/render" }
storage = { path = "../../crates/storage" }
