[package]
name = "security"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.11.1"
ed25519-dalek = "3.0.0"
platform-apis = { version = "0.1.0", path = "../platform-apis" }
sha2 = "0.11.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Threading"] }
