[package]
name = "profile"
version = "0.1.0"
edition = "2021"

[dependencies]
ipc = { path = "../ipc" }
security = { path = "../security" }
net = { path = "../net" }
storage = { path = "../storage" }
platform-apis = { path = "../platform-apis" }
neutron = { path = "../neutron" }
url = "2.5.8"

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }

[[bin]]
name = "profile-worker"
path = "src/bin/profile_worker/main.rs"
