[package]
name = "profile"
version = "0.1.0"
edition = "2021"

[dependencies]
ipc = { path = "../ipc" }
dom = { path = "../dom" }
html = { path = "../html" }
css = { path = "../css" }
layout-engine = { path = "../layout-engine" }
render = { path = "../render" }
security = { path = "../security" }
js-runtime = { path = "../js-runtime" }
net = { path = "../net" }
storage = { path = "../storage" }
url = "2.5.8"

[[bin]]
name = "profile-worker"
path = "src/bin/profile_worker.rs"
