[package]
name = "js-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
quickjs-sys = { path = "quickjs-sys" }
dom = { path = "../dom" }
html = { path = "../html" }
css = { path = "../css" }
platform-apis = { path = "../platform-apis" }
net = { path = "../net" }
storage = { path = "../storage" }
url = "2.5.8"
urlencoding = "2.1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "hot_loop"
harness = false
